### ISSUE TITLE
GOPATH yogo stopped

### ISSUE THREAD

**Issue by giansalex** [andriylesch/generator-yogo#11]
`
YoGo generator will only generate project in 'GOPATH/src/<YOUR_PROJECT> director           y'. Otherwise the generation will be stopped.
`
![image](https://user-images.githubusercontent.com/14926587/37802056-e2027236-2df6-11e8-896d-5f3dd05498f5.png)

**Comment by andriylesch** [comment]
Hello @giansalex

Thank you for your issue. I  will check this problem, and soon will come back to you.
Can you provide a little more detail, please.
Like version of windows and  nodejs.

BR,
Andrii Lesch

**Comment by giansalex** [comment]
Hello @andriylesch 
Windows: **Windows 7 Ultimate** 6.1.7601 Service Pack 1
Nodejs: **v8.9.4**
Npm:  **5.6.0**
Go:  **go1.10**

**Comment by giansalex** [comment]
I found the problem:
https://github.com/andriylesch/generator-yogo/blob/bf21c6f5e3fcbba5cebaad6984484fd47fc1077f/generators/app/index.js#L13

yogo expect:  `C:/Users/Administrador/go/src/yogo_rest`
current:  `C:\Users\Administrador\go\src\yogo_rest`

**Comment by andriylesch** [comment]
Hello @giansalex 

Thank you very much, i have found the same.
Next release will fix it.

Best regards,
Andriy Lesch
